### ISSUE TITLE
Issues raised in the morning session

### ISSUE THREAD

**Issue by John-Kibirige** [DebbyMiressa/DebbyMiressa.github.io#6]
## All issues that were raised 

- Use CSS grid instead of flexbox for the recent works section for the desktop version.
- Add comments on every top-level element in your markup for easy identification
- Add spaces in your code to make it more readable

**Comment by DebbyMiressa** [comment]
Thanks, guys for the comments 👍 👍 I have dealt with the issues that were raised here.
