### ISSUE TITLE
peer-to-peer code reviews 1

### ISSUE THREAD

**Issue by Rn486** [DebbyMiressa/DebbyMiressa.github.io#8]
**Your project really looks good.**

- I love your choice of animations
- You have really made the project look like the template shared.
- All your pictures are in the right place.
Just one thing, have you considered to align the last button with the social-media icons? This will make your project look like the template shared and will improve the overall usability.

**Comment by aceDavon** [comment]
Great work so far, I see you've done good work to replicate the design on your end. There are a few additions and adjustments I think you could make;

1. You could make the name text on the Navbar align with the vertical icons on the jumbotron section. This will help introduce consistency across the project. You could achieve it with the justify-content: space-evenly or space-around from your styles.css
2. Make a button appearance on the hover effect on the lower cards. This will make the project look like the template on Figma.
3. Align the last group of icons on the footer section to be in line with the last button from the section before so you could have the same design as the Figma. You could make the container smaller and then place it in the center, afterwards you could justify the icons to flex-start.
All these suggestions are on the desktop version.

**Comment by DebbyMiressa** [comment]
Thanks, Recillah and David, I will integrate your suggestions in my next commit/push. 👍 🙇
